#!/bin/bash
# if block is clicked (left) -> trigger simple calendar
if [[ 1 -eq ${BLOCK_BUTTON} ]];then
	# (set config to close on deselect)
	gsimplecal &
fi
# [doy] yyyy-mm-dd hh:mm
echo " [$(date +%j)]  $(date '+%Y-%m-%d %H:%M')"
